# Generated by Django 6.0.3 on 2026-03-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_artwork_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='artwork_type',
            field=models.CharField(choices=[('painting', 'Painting'), ('wall_decoration', 'Wall Decoration'), ('lamp', 'Lamp'), ('tray', 'Tray'), ('decor_piece', 'Decor Piece')], default='painting', max_length=30),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='height_cm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='medium',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='width_cm',
            field=models.IntegerField(),
        ),
    ]
