# Generated by Django 6.0.3 on 2026-03-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_artwork_artwork_type_alter_artwork_height_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='custom_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artwork',
            name='price_on_request',
            field=models.BooleanField(default=False),
        ),
    ]
