# Generated by Django 6.0.3 on 2026-03-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_artwork_custom_available_artwork_price_on_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='artwork_type',
            field=models.CharField(choices=[('painting', 'Painting'), ('wall_decoration', 'Wall Decoration'), ('lamp', 'Lamp'), ('tray', 'Tray'), ('decor_piece', 'Decor Piece'), ('accessory', 'Accessory')], default='painting', max_length=30),
        ),
    ]
