# Generated by Django 6.0.3 on 2026-03-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_artwork_artwork_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['-created_at'], 'verbose_name': 'Artwork', 'verbose_name_plural': 'Artworks'},
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='custom_available',
            new_name='is_collaboration',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='price_eur',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='price_on_request',
        ),
        migrations.AddField(
            model_name='artwork',
            name='depth_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='main_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='artwork',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artwork_type',
            field=models.CharField(choices=[('painting', 'Painting'), ('wall_decoration', 'Wall Decoration'), ('lamp', 'Lamp'), ('tray', 'Tray'), ('decor_piece', 'Decor Piece'), ('accessory', 'Accessory')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('acquired', 'Acquired')], db_index=True, default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True),
        ),
        migrations.DeleteModel(
            name='ArtworkImage',
        ),
    ]
