# Generated by Django 6.0.3 on 2026-03-30 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_alter_artwork_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='main_image_url',
        ),
        migrations.CreateModel(
            name='ArtworkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artworks/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_main', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.artwork')),
            ],
            options={
                'verbose_name': 'Artwork image',
                'verbose_name_plural': 'Artwork images',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
