# Generated by Django 6.0.3 on 2026-03-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_remove_artwork_main_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='materials',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
