# Generated by Django 6.0.3 on 2026-03-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_artwork_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='diameter_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True),
        ),
    ]
