# Generated by Django 6.0.3 on 2026-03-31 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_artwork_diameter_cm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='diameter_cm',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='materials',
        ),
        migrations.AddField(
            model_name='artwork',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='main_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.DeleteModel(
            name='ArtworkImage',
        ),
    ]
