# Generated by Django 6.0.3 on 2026-04-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_artworkimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='artworkimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/'),
        ),
    ]
