# Generated by Django 6.0.3 on 2026-03-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('paid', 'Paid'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
