# Generated by Django 6.0.3 on 2026-03-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_purchaserequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes for review, production, or follow-up.'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='approved_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final approved price for this request.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='payment_link',
            field=models.URLField(blank=True, help_text='Stripe or payment link sent to the customer.'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('payment_sent', 'Payment Sent'), ('paid', 'Paid'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
