# Generated by Django 6.0.3 on 2026-03-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_purchaserequest_admin_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='stripe_session_id',
            field=models.CharField(blank=True, help_text='Stripe Checkout Session ID for this request.', max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='payment_link',
            field=models.URLField(blank=True, help_text='Stripe Checkout link sent to the customer.'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('payment_sent', 'Payment Sent'), ('deposit_paid', 'Deposit Paid'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
