# Generated by Django 6.0.3 on 2026-03-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_purchaserequest_stripe_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('payment_sent', 'Payment Sent'), ('paid', 'Paid'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
