# Generated by Django 6.0.3 on 2026-03-30 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_purchaserequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('artwork_type', models.CharField(choices=[('painting', 'Painting'), ('wall_decoration', 'Wall Decoration'), ('lamp', 'Lamp'), ('tray', 'Tray'), ('decor_piece', 'Decor Piece'), ('accessory', 'Accessory')], db_index=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('depth_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('acquired', 'Acquired')], db_index=True, default='available', max_length=20)),
                ('is_collaboration', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artwork',
                'verbose_name_plural': 'Artworks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtworkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artworks/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_main', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.artwork')),
            ],
            options={
                'verbose_name': 'Artwork image',
                'verbose_name_plural': 'Artwork images',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='PurchaseRequest',
        ),
    ]
